from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def build_segments(frame: pd.DataFrame) -> tuple[list[tuple[str, int, int]], int]:
    events = frame.reset_index().rename(columns={"index": "order"})
    events = events.sort_values(["time", "order"])
    segments: list[tuple[str, int, int]] = []
    current_task: str | None = None
    current_start: int | None = None
    end_time = int(events["time"].max()) if not events.empty else 0

    for row in events.itertuples(index=False):
        event = row.event
        task = row.task
        time = int(row.time)

        if event == "dispatch":
            if current_task is not None and current_start is not None and current_start < time:
                segments.append((current_task, current_start, time))
            current_task = task
            current_start = time
            continue

        if event in {"preempt", "complete"} and current_task == task and current_start is not None:
            if current_start < time:
                segments.append((task, current_start, time))
            current_task = None
            current_start = None

    if current_task is not None and current_start is not None and current_start < end_time:
        segments.append((current_task, current_start, end_time))

    return segments, end_time


def build_idle_segments(
    segments: list[tuple[str, int, int]],
    end_time: int
) -> list[tuple[str, int, int]]:
    idle: list[tuple[str, int, int]] = []
    cursor = 0

    for _, start, stop in sorted(segments, key=lambda item: item[1]):
        if cursor < start:
            idle.append(("IDLE", cursor, start))
        cursor = max(cursor, stop)

    if cursor < end_time:
        idle.append(("IDLE", cursor, end_time))

    return idle


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot a task timeline from simulator trace CSV.")
    parser.add_argument("trace_csv", type=Path, help="Trace CSV generated by --trace-csv")
    parser.add_argument("output_png", type=Path, help="Output PNG path")
    parser.add_argument("--title", default="Scheduler Timeline", help="Plot title")
    args = parser.parse_args()

    frame = pd.read_csv(args.trace_csv)
    segments, end_time = build_segments(frame)
    idle_segments = build_idle_segments(segments, end_time)
    task_names = sorted({task for task, _, _ in segments})
    rows = task_names + ["IDLE"]
    y_positions = {task: index for index, task in enumerate(rows)}
    cmap = plt.get_cmap("tab20")

    fig, ax = plt.subplots(figsize=(12, 1.2 * max(len(rows), 4)))

    for index, task in enumerate(task_names):
        bars = [(start, stop - start) for task_name, start, stop in segments if task_name == task]
        ax.broken_barh(bars, (y_positions[task] - 0.4, 0.8), facecolors=cmap(index))

    if idle_segments:
        idle_bars = [(start, stop - start) for _, start, stop in idle_segments]
        ax.broken_barh(idle_bars, (y_positions["IDLE"] - 0.4, 0.8), facecolors="#d9d9d9")

    release_rows = frame[frame["event"] == "release"]
    preempt_rows = frame[frame["event"] == "preempt"]
    for row in release_rows.itertuples(index=False):
        ax.scatter(int(row.time), y_positions.get(row.task, 0), marker="v", s=32, color="black")
    for row in preempt_rows.itertuples(index=False):
        ax.axvline(int(row.time), color="#bb3333", linestyle="--", linewidth=0.8, alpha=0.4)

    ax.set_xlim(0, max(end_time, 1))
    ax.set_ylim(-1, len(rows))
    ax.set_yticks([y_positions[name] for name in rows])
    ax.set_yticklabels(rows)
    ax.set_xlabel("Time (cycles)")
    ax.set_title(args.title)
    ax.grid(axis="x", linestyle="--", alpha=0.3)
    fig.tight_layout()
    fig.savefig(args.output_png, dpi=180)
    plt.close(fig)


if __name__ == "__main__":
    main()
