from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def plot_matrix(ax: plt.Axes, matrix: pd.DataFrame, title: str) -> None:
    image = ax.imshow(matrix.values, cmap="Blues")
    ax.set_xticks(range(len(matrix.columns)))
    ax.set_yticks(range(len(matrix.index)))
    ax.set_xticklabels(matrix.columns, rotation=45, ha="right")
    ax.set_yticklabels(matrix.index)
    ax.set_title(title)
    plt.colorbar(image, ax=ax, fraction=0.046, pad=0.04)

    for row_index, row_name in enumerate(matrix.index):
        for col_index, column_name in enumerate(matrix.columns):
            value = matrix.loc[row_name, column_name]
            ax.text(col_index, row_index, int(value), ha="center", va="center", color="black")


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot pairwise CRPD attribution heatmaps.")
    parser.add_argument("pairwise_csv", type=Path, help="Pairwise CSV generated by --pairwise-csv")
    parser.add_argument("output_png", type=Path, help="Output PNG path")
    args = parser.parse_args()

    frame = pd.read_csv(args.pairwise_csv)
    if frame.empty:
        raise SystemExit("Pairwise CSV is empty.")

    tasks = sorted(set(frame["victim_task"]) | set(frame["source_task"]))
    crpd_matrix = (
        frame.pivot_table(
            index="victim_task",
            columns="source_task",
            values="attributed_crpd_cycles",
            aggfunc="sum",
            fill_value=0,
        )
        .reindex(index=tasks, columns=tasks, fill_value=0)
    )
    eviction_matrix = (
        frame.pivot_table(
            index="victim_task",
            columns="source_task",
            values="evictions_while_preempted",
            aggfunc="sum",
            fill_value=0,
        )
        .reindex(index=tasks, columns=tasks, fill_value=0)
    )

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    plot_matrix(axes[0], crpd_matrix, "Attributed CRPD Cycles")
    plot_matrix(axes[1], eviction_matrix, "Evictions While Victim Preempted")
    fig.tight_layout()
    fig.savefig(args.output_png, dpi=180)
    plt.close(fig)


if __name__ == "__main__":
    main()
